languaje: bash

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "IkerST"
      - git config --local user.email "ikersanditrejo@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
   provider: releases
   api_key: a6cd7271cb1114cce9b27799807af1bdc52c6d80
   file: $PWD/Anykernel2/harpia/*.zip
   skip_cleanup: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk

script:
  - bash harpia.sh
